stages:
  - synth_st
  - pnr_st
  - pack_st

synth:
  stage: synth_st
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - >
      for i in blinky passthru;
      do
      pushd ${i}/OpenSource;
      make ${i}.json;
      popd;
      done
  artifacts:
    paths:
    - blinky/OpenSource/blinky.json
    - passthru/OpenSource/passthru.json
    expire_in: 1 week

pnr:
  stage: pnr_st
  image: hdlc/nextpnr:ecp5
  before_script:
    - apt update -qq && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends make
    - nextpnr-ecp5 --version
  script:
    - touch */*/*.json
    - pushd blinky/OpenSource
    - make ulx3s_out.config
    - popd
    - pushd passthru/OpenSource
    - make ulx3s_out.config
  artifacts:
    paths:
    - blinky/OpenSource/ulx3s_out.config
    - passthru/OpenSource/ulx3s_out.config
    expire_in: 1 week

pack:
  stage: pack_st
  image: hdlc/prjtrellis
  before_script:
    - ecppack --version
  script:
    - touch */*/*.json
    - touch */*/ulx3s_out.config
    - pushd blinky/OpenSource
    - make ulx3s.bit
    - popd
    - pushd passthru/OpenSource
    - make ulx3s.bit
  artifacts:
    paths:
    - blinky/OpenSource/ulx3s.bit
    - passthru/OpenSource/ulx3s.bit
    expire_in: 1 week
