stages:
  - synth_pnr_st
  - pack_st

synth:
  stage: synth_pnr_st
  image: hdlc/impl
  before_script:
    - yosys --version
    - nextpnr-ecp5 --version
  script:
    - >
      for i in blinky passthru;
      do set -e;
      pushd ${i}/OpenSource;
      make ${i}.json;
      make ulx3s_out.config;
      popd;
      done
  artifacts:
    paths:
    - blinky/OpenSource/blinky.json
    - blinky/OpenSource/ulx3s_out.config
    - passthru/OpenSource/passthru.json
    - passthru/OpenSource/ulx3s_out.config
    expire_in: 1 week

pack:
  stage: pack_st
  image: hdlc/prjtrellis
  before_script:
    - ecppack --version
  script:
    - >
      for i in blinky passthru;
      do set -e;
      pushd ${i}/OpenSource;
      ecppack ulx3s_out.config ulx3s.bit;
      popd;
      done
  artifacts:
    paths:
    - blinky/OpenSource/ulx3s.bit
    - passthru/OpenSource/ulx3s.bit
    expire_in: 1 week
